### ISSUE TITLE
Thumbnail not appear on Control Bar

### ISSUE THREAD

**Issue by Dimitargabres** [phloxic/videojs-sprite-thumbnails#42]
Hi team

I can't sure that this is issue or not, but i need help, so that raise this ticket.

Currently i am using videojs on react and i want to use sprite-thumbnail.
What i have done is

```
const player = (playerRef.current = videojs(
  videoElement,
  options,
  () => {
    player.spriteThumbnails({
      interval: 2,
      url: `/assets/preview_01.jpg`,
      width: 160,
      height: 90,
    })
  },
))
```

But on timeline, thumbnail is not showing, just time is displayed.
![image](https://user-images.githubusercontent.com/93514480/208873594-6905cf63-e0fc-4201-bc11-035fad88469d.png)

When i check player on console, `player.spriteThumbnails` is a function not object.

![image](https://user-images.githubusercontent.com/93514480/208873882-f6f1f2a5-a457-49e2-a98f-46dd83b83fdb.png)

Did i something wrong?

Kindly update me.

Regard.

**Comment by phloxic** [comment]
Indeed `player.spriteThumbnails` is used when the player is already set up, as in most of the examples in the README.

However, you can configure the plugin directly
- as a property of the `plugins` object on the player level or
- as a property of the media sources

The [playlist example](https://github.com/phloxic/videojs-sprite-thumbnails#playlist-example) shows both of the above.

In your case:

```js
const player = (playerRef.current = videojs(videoElement, {
  // various config options
  plugins: { // configure plugins
    spriteThumbnails: {
      interval: 2,
      url: '/assets/preview_01.jpg',
      width: 160,
      height: 90
    }
  }
));
```

I will try to clarify this a bit more in the docs when I find time.

**Comment by Dimitargabres** [comment]
Hello

Thanks for your post.

Actually, i tried it as well, but it is also not working.

**Comment by phloxic** [comment]
@Dimitargabres - works [for me](https://phloxic.productions/test/videojs/sprite-thumbnails-3.html)[tm]

**Comment by Dimitargabres** [comment]
Hello
Thank you.

But even from the link, i can't see thumb

![image](https://user-images.githubusercontent.com/93514480/209149680-036fdb80-865c-4736-9f5b-96b2cb249bdc.png)

**Comment by phloxic** [comment]
In which browser and on what platform is this happening?

**Comment by Dimitargabres** [comment]
I test with google chrome, Microsoft Edge

**Comment by phloxic** [comment]
I don't have a windows machine to test right now, sorry. Definitely works in Chrome, Firefox, Safari etc. for me.

Do you get any errors? Is the thumbnail file loaded?

**Comment by Dimitargabres** [comment]
What i can see from console log is only this.

![image](https://user-images.githubusercontent.com/93514480/209152533-df0eaf5d-834f-4d23-928a-05cdc4ec4e5d.png)

Can you show me screenshot of how thumbnail shows on your side please?

**Comment by Dimitargabres** [comment]
PS: Also for me, i am seeing 
`VIDEOJS: player: spritehumbnails: WARN: connection.downlink < 2`

Is that one can be reason?

**Comment by phloxic** [comment]
Yes, your connection seems rather slow, see the `downlink` [option](https://github.com/phloxic/videojs-sprite-thumbnails#configuration).

Set it to `0`, at least for testing.

**Comment by phloxic** [comment]
<img width="258" alt="Screen Shot 2022-12-22 at 14 20 16" src="https://user-images.githubusercontent.com/168338/209154331-a2ce89c5-cd0e-4543-87a2-feba1ce5efa5.png">

**Comment by Dimitargabres** [comment]
Wow, working, when i set `downlink: 0`

Thank you very much.

I love this package!!!

**Comment by cedricve** [comment]
Works
      downlink: 0,



downlink
--


<br class="Apple-interchange-newline">

downlink
--


<br class="Apple-interchange-newline">
