### ISSUE TITLE
Can't get thumbnails to show

### ISSUE THREAD

**Issue by legocabin** [phloxic/videojs-sprite-thumbnails#46]
I'm using videojs version 7.20.2 and followed approximately this tutorial
https://giriaakula.medium.com/videojs-how-to-create-preview-thumbnails-8ce273974529. 

I added the plug-in using CDN
`<script src="https://unpkg.com/videojs-sprite-thumbnails@0.6.0/dist/videojs-sprite-thumbnails.min.js"></script>`

and added it to the player like this
`player.spriteThumbnails({
        interval:1,
        url: thumbnailpreviewurl,
        width: 160,
        height: 90
      }).log.level('debug');`

I'm not getting any indication that the plugin is working other than `vjs-sprite-thumbnails` show up as a class name in on of the video divs and it doesn't seem like I'm getting any console error messages. Do you have any directions for debugging?

**Comment by phloxic** [comment]
Hi @legocabin - could you provide a minimal sample page like [this one](http://phloxic.test/test/videojs/sprite-thumbnails.html), which basically uses the same setup (but works)? Thanks.

**Comment by phloxic** [comment]
No feedback, closing.
